// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsiazPjIoljwaQ32Kb6Ev7ZIx88Ie00x8',
    appId: '1:1051907646227:web:ba6c8fa1345894ccccb0e6',
    messagingSenderId: '1051907646227',
    projectId: 'nyeinchanmoe-b6993',
    authDomain: 'nyeinchanmoe-b6993.firebaseapp.com',
    storageBucket: 'nyeinchanmoe-b6993.appspot.com',
    measurementId: 'G-3NYJE21BVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdE8c8V1wsJVpFUiA5KMMUxx_63-Covm4',
    appId: '1:1051907646227:android:6137570baf8c4414ccb0e6',
    messagingSenderId: '1051907646227',
    projectId: 'nyeinchanmoe-b6993',
    storageBucket: 'nyeinchanmoe-b6993.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtZyxqN9cm31CmxWyWoKZFG7F126K7lMU',
    appId: '1:1051907646227:ios:001dff84480deb8accb0e6',
    messagingSenderId: '1051907646227',
    projectId: 'nyeinchanmoe-b6993',
    storageBucket: 'nyeinchanmoe-b6993.appspot.com',
    androidClientId:
        '1051907646227-gmumulpqa1ishkiln23v5sf3og18k5d7.apps.googleusercontent.com',
    iosClientId:
        '1051907646227-omh968bec9m30igm1qe77c5el6cfgvp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtZyxqN9cm31CmxWyWoKZFG7F126K7lMU',
    appId: '1:1051907646227:ios:eb3ac450a8213ca2ccb0e6',
    messagingSenderId: '1051907646227',
    projectId: 'nyeinchanmoe-b6993',
    storageBucket: 'nyeinchanmoe-b6993.appspot.com',
    androidClientId:
        '1051907646227-gmumulpqa1ishkiln23v5sf3og18k5d7.apps.googleusercontent.com',
    iosClientId:
        '1051907646227-n54h9bf1rpl6n9k515e04bceoidjtaul.apps.googleusercontent.com',
    iosBundleId: 'com.example.newProject.RunnerTests',
  );
}
